system:
  num_workers : 4
  seed : 0
  tensorboard : True


image_param:
  size: 256
  band : 100
  type : 'RE' #choice ['RE', 'RA']

path:
  dataset_path : '/root/work/hjr/dataset/4.mat'
  train_csv: '/root/work/hjr/dataset/train_RA.csv'
  val_csv: '/root/work/hjr/dataset/val_RA.csv'
  test_csv: '/root/work/hjr/dataset/train_RE_test_best_temp.csv'
  output_dir : 'output/output_231119_server2_RA_cosinealr'
  #model_path : 'output/output_231119_server2_RA_cosinealr/pths/best_checkpoint_OA.pth'
  model_path : 'output/231122_mfA100_RE_cosinealr_nadam_p3_bp3_clip65535_mirror_sp256_lr001_adam/pths/best_checkpoint_OA.pth'
  # model_path : 'output/output_231119_server2_RA_cosinealr/pths/best_checkpoint_OA.pth'
  

dataset: 'hjr'
num_class : 31



network:
  arch : 'SF' #choice ['SF', 'DL'] SF:SpectralFormer / DL : DeepLab V3+
  spectralformer:
    patch : 3
    band_patch : 3
    sampling_num : 64
    mode : 'CAF' #choice ['ViT', 'CAF']
  DeepLab:
    output_stride : 16 #choice [8,16]
    separable_conv : False
    model : 'deeplabv3plus_mobilenet' #choice ['deeplabv3plus_mobilenet', 'deeplabv3plus_xception', ...]



train_param:
  epoch : 300000
  train_batch: 16
  val_batch : 16
  pixel_batch : 4096 #1024
  eval_freq : 2
  test_freq : 2
  save_freq : 50
  learning_rate : 0.0005
  gamma : 0.9
  weight_decay : 0
  opt : 'adam' #choide ['adam','nadam']
  lrs : 'cosinealr' #choice ['steplr', 'cosinealr']
  resume : True

test_param: 
  test_batch : 1
  sampling_num : 256
  save_img : False #True
  out_img_path : 'output/output_temp/231122_mfA100_RE_cosinealr_nadam_p3_bp3_clip65535_mirror_sp256_lr001_adam'

