system:
  num_workers : 8
  seed : 0
  tensorboard : True


image_param:
  size: 256
  band : 100
  type : 'RA' #choice ['RE', 'RA']

path:
  dataset_path : '/root/work/hjr/dataset/4.mat_old'
  train_csv: '/root/work/hjr/dataset/train_RA.csv'
  val_csv: '/root/work/hjr/dataset/val_RA.csv'
  test_csv: '/root/work/hjr/dataset/test_RA.csv'
  output_dir : 'output/output_231114_RA_norm_clipping40000'
  model_path : 'output/output_231114_RA_norm_clipping40000/pths/best_checkpoint_OA.pth'
  

dataset: 'hjr'
num_class : 30



network:
  arch : 'SF' #choice ['SF', 'DL'] SF:SpectralFormer / DL : DeepLab V3+
  spectralformer:
    patch : 1
    band_patch : 3
    sampling_num : 64
    mode : 'CAF' #choice ['ViT', 'CAF']
  DeepLab:
    output_stride : 16 #choice [8,16]
    separable_conv : False
    model : 'deeplabv3plus_mobilenet' #choice ['deeplabv3plus_mobilenet', 'deeplabv3plus_xception', ...]



train_param:
  epoch : 3000
  train_batch: 16
  val_batch : 16
  pixel_batch : 1024
  eval_freq : 2
  test_freq : 2
  save_freq : 30
  learning_rate : 0.0005
  gamma : 0.9
  weight_decay : 0
  opt : 'adam' #choide ['adam','nadam']
  lrs : 'steplr' #choice ['steplr', 'cosinealr']
  resume : True

test_param:
  test_batch : 1

  
